# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=100, verbose_name='bug名称')),
                ('bug_desc', models.CharField(max_length=200, verbose_name='bug描述')),
                ('bug_status', models.CharField(choices=[('激活', '激活'), ('已解决', '已解决'), ('已关闭', '已关闭')], default='激活', max_length=200, null=True, verbose_name='解决状态')),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=3, max_length=200, null=True, verbose_name='严重程度')),
                ('bug_creater', models.CharField(max_length=200, verbose_name='创建人')),
                ('bug_assign', models.CharField(max_length=200, verbose_name='分配给')),
                ('crete_time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
